import * as React from "react"
import { cn } from "@/registry/lib/utils"
import { Popover, PopoverContent, PopoverTrigger } from "@/registry/ui/popover"

/**
 * AILabel — marks content or controls GENERATED or AUTOFILLED by AI, and explains how.
 * Mandatory wherever AI produced a value the user may rely on. Clicking opens an explainability popover.
 * Pair with the `ai-gradient-border` surface on the AI-touched container. Revert → restore the user's value.
 */
export function AILabel({ size = "md", children, title = "AI explained", className, onRevert }: {
  size?: "xs" | "sm" | "md"
  /** Explainability content: what the model did, confidence, source/model name. */
  children?: React.ReactNode
  title?: string
  className?: string
  /** When the AI changed a user value, offer a way back. */
  onRevert?: () => void
}) {
  const s = { xs: "h-4 px-1 text-[0.625rem]", sm: "h-5 px-1.5 text-caption", md: "h-6 px-2 text-caption" }[size]
  return (
    <span className="inline-flex items-center gap-1">
      <Popover>
        <PopoverTrigger
          aria-label="AI – Show information"
          className={cn("inline-flex items-center rounded-sm ai-gradient-border font-semibold tracking-wide ai-gradient-text focus-ring", s, className)}
        >
          AI
        </PopoverTrigger>
        <PopoverContent className="w-80 ai-gradient-border" caret>
          <p className="text-caption font-semibold ai-gradient-text">AI</p>
          <p className="mt-1 text-headline">{title}</p>
          <div className="mt-2 text-body text-muted-foreground">{children ?? "This content was generated by AI. Review it before relying on it."}</div>
        </PopoverContent>
      </Popover>
      {onRevert && (
        <button type="button" onClick={onRevert} className="rounded-sm px-1 text-caption text-link hover:underline focus-ring">
          Revert to AI input
        </button>
      )}
    </span>
  )
}

/** AISurface — container treatment for AI-generated regions (tiles, table cells, fields). */
export function AISurface({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("scope-lg ai-gradient-border p-4", className)} {...props} />
}
