import * as React from "react"
import { cn } from "@/registry/lib/utils"
import { Popover, PopoverContent, PopoverTrigger } from "@/registry/ui/popover"

/**
 * AILabel — marks content or controls GENERATED or AUTOFILLED by AI, and explains how.
 * Mandatory wherever AI produced a value the user may rely on. Clicking opens an explainability popover.
 * Tone: rainbow when standing alone; muted (white, low opacity) inside another component.
 */
export function AILabel({ size = "md", children, title = "AI explained", className, onRevert, tone = "auto" }: {
  size?: "xs" | "sm" | "md"
  /** Explainability content: what the model did, confidence, source/model name. */
  children?: React.ReactNode
  title?: string
  className?: string
  /** When the AI changed a user value, offer a way back. */
  onRevert?: () => void
  /**
   * auto (default): rainbow when standing alone; muted inside another component
   * (field, notification, tile, AI surface — anything marked data-ai-context). Force with spectrum | muted.
   */
  tone?: "auto" | "spectrum" | "muted"
}) {
  const s = { xs: "h-4 px-1 text-[0.625rem]", sm: "h-5 px-1.5 text-caption", md: "h-6 px-2 text-caption" }[size]
  return (
    <span className="inline-flex items-center gap-1">
      <Popover>
        <PopoverTrigger
          aria-label="AI – Show information"
          className={cn(
            "inline-flex items-center rounded-sm font-semibold tracking-wide focus-ring",
            tone !== "muted" && "ai-gradient-border",
            tone === "auto" &&
              "in-data-[ai-context]:border in-data-[ai-context]:border-border-strong! in-data-[ai-context]:bg-none! in-data-[ai-context]:bg-transparent! in-data-[ai-context]:animate-none! in-data-[ai-context]:[&>span]:bg-none! in-data-[ai-context]:[&>span]:text-foreground/60!",
            tone === "muted" && "border border-border-strong bg-none bg-transparent [&>span]:bg-none! [&>span]:text-foreground/60!",
            s,
            className,
          )}
        >
          {/* Text gradient lives on its own span so it never overrides the rainbow border. */}
          <span className="ai-gradient-text">AI</span>
        </PopoverTrigger>
        <PopoverContent className="w-80 ai-gradient-border" caret>
          <p className="text-caption font-semibold"><span className="ai-gradient-text">AI</span></p>
          <p className="mt-1 text-headline">{title}</p>
          <div className="mt-2 text-body text-muted-foreground">{children ?? "This content was generated by AI. Review it before relying on it."}</div>
        </PopoverContent>
      </Popover>
      {onRevert && (
        <button type="button" onClick={onRevert} className="rounded-sm px-1 text-caption text-link underline decoration-transparent hover:decoration-current focus-ring">
          Revert to AI input
        </button>
      )}
    </span>
  )
}

/** AISurface — container treatment for AI-generated regions (tiles, table cells, fields). Labels inside go muted. */
export function AISurface({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div data-ai-context="" className={cn("scope-lg ai-gradient-border p-3", className)} {...props} />
}
