import * as React from "react"
import { cn } from "@/registry/lib/utils"
import { cachedShape, measurePictogram, rememberShape, roundedPath, type PictogramShape } from "@/registry/lib/pictogram-shape"

/**
 * Pictogram, large illustrative symbols (from @/registry/pictograms) for empty states, onboarding and tiles.
 * Drawn in Vita's hand: every corner is rounded (never sharp) to the theme's radius, lines take the theme's weight.
 *
 * Never use a pictogram as a button or at less than 48px; use Icon instead.
 */
/** md 48 · lg 64 · xl 80 */
const sizeClass = { md: "size-12", lg: "size-16", xl: "size-20" } as const

type PictogramComponent = React.ComponentType<{ className?: string; "aria-hidden"?: boolean; "aria-label"?: string; role?: string }>

/**
 * A Vita pictogram: its centre lines (generated by scripts/build-pictograms.mjs). Each line has a width, and is
 * closed or open; points are flat [x, y, x, y…] in the drawing's units.
 */
export interface PictogramData {
  w: number
  h: number
  l: { w: number; c: boolean; p: number[] }[]
}
const isData = (x: unknown): x is PictogramData => typeof x === "object" && x !== null && "l" in x

export interface PictogramProps {
  /** A pictogram from @/components/vita/pictograms. */
  as: PictogramData | PictogramComponent
  size?: keyof typeof sizeClass
  tone?: "neutral" | "brand"
  label?: string
  className?: string
}

/* The theme's radius, live: the theme editor (or a product) can change --vita-radius at any time. One observer for
   every pictogram on the page. */
const listeners = new Set<() => void>()
let observer: MutationObserver | null = null
function subscribe(fn: () => void) {
  listeners.add(fn)
  if (!observer && typeof MutationObserver !== "undefined") {
    observer = new MutationObserver(() => listeners.forEach((l) => l()))
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ["style", "class", "data-theme"] })
  }
  return () => {
    listeners.delete(fn)
    if (!listeners.size) { observer?.disconnect(); observer = null }
  }
}
function cssPx(name: string, fallback: number) {
  if (typeof window === "undefined") return fallback
  const root = document.documentElement
  const v = getComputedStyle(root).getPropertyValue(name).trim()
  const n = parseFloat(v)
  if (!Number.isFinite(n)) return fallback
  return v.endsWith("rem") ? n * parseFloat(getComputedStyle(root).fontSize) : n
}
const linePx = () => cssPx("--vita-line", 0.5)
const px = { md: 48, lg: 64, xl: 80 } as const

/** A centre line as path data: every bend rounded to r (clamped to the segments either side). */
function lineD(p: number[], closed: boolean, r: number): string {
  const n = p.length / 2
  const pt = (i: number): [number, number] => [p[2 * i], p[2 * i + 1]]
  if (n < 2) return ""
  if (n === 2 || r <= 0) return "M" + Array.from({ length: n }, (_, i) => pt(i).join(" ")).join("L") + (closed ? "Z" : "")
  const corner = (i: number) => {
    const a = pt((i - 1 + n) % n), v = pt(i), b = pt((i + 1) % n)
    const l1 = Math.hypot(v[0] - a[0], v[1] - a[1]) || 1, l2 = Math.hypot(b[0] - v[0], b[1] - v[1]) || 1
    const k = Math.min(r, l1 / 2, l2 / 2)
    const s: [number, number] = [v[0] + ((a[0] - v[0]) / l1) * k, v[1] + ((a[1] - v[1]) / l1) * k]
    const e: [number, number] = [v[0] + ((b[0] - v[0]) / l2) * k, v[1] + ((b[1] - v[1]) / l2) * k]
    return `L${s[0].toFixed(2)} ${s[1].toFixed(2)}Q${v[0]} ${v[1]} ${e[0].toFixed(2)} ${e[1].toFixed(2)}`
  }
  if (closed) {
    let d = ""
    for (let i = 0; i < n; i++) d += corner(i)
    return "M" + d.slice(1) + "Z"
  }
  let d = `M${pt(0).join(" ")}`
  for (let i = 1; i < n - 1; i++) d += corner(i)
  return d + `L${pt(n - 1).join(" ")}`
}

/** A generated pictogram: its lines, round-capped and round-joined, every bend rounded to the theme. */
function LinePictogram({ data, size, r, extra, a11y, className }: { data: PictogramData; size: keyof typeof sizeClass; r: number; extra: number; a11y: object; className: string }) {
  // The line weight knob, in the drawing's units at this size.
  const add = (extra * data.w) / px[size]
  return (
    <span {...a11y} className={className}>
      <svg aria-hidden viewBox={`0 0 ${data.w} ${data.h}`} className="size-full overflow-visible" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round">
        {data.l.map((l, i) => <path key={i} d={lineD(l.p, l.c, r)} strokeWidth={l.w + add} />)}
      </svg>
    </span>
  )
}

function radiusPx() {
  if (typeof window === "undefined") return 8
  const v = getComputedStyle(document.documentElement).getPropertyValue("--vita-radius").trim()
  const n = parseFloat(v)
  if (!Number.isFinite(n)) return 8
  return v.endsWith("rem") ? n * parseFloat(getComputedStyle(document.documentElement).fontSize) : n
}
/** Corner radius in pictogram units (a 32-unit drawing): never sharp (0.35 at a square theme), softer as the theme is. */
const cornerUnits = (px: number) => 0.35 + px * 0.11

export function Pictogram({ as, size = "lg", tone = "brand", label, className }: PictogramProps) {
  const radius = React.useSyncExternalStore(subscribe, radiusPx, () => 8)
  const extra = React.useSyncExternalStore(subscribe, linePx, () => 0.5)
  if (isData(as)) {
    const a11y = { "aria-hidden": label ? undefined : true, "aria-label": label, role: label ? "img" : undefined }
    return <LinePictogram data={as} size={size} r={cornerUnits(radius)} extra={extra} a11y={a11y} className={cn("relative inline-flex shrink-0", sizeClass[size], tone === "brand" ? "text-primary" : "text-muted-foreground", className)} />
  }
  return <OutlinePictogram Glyph={as} size={size} tone={tone} label={label} className={className} radius={radius} />
}

/** A Carbon pictogram component (not yet generated as lines): its outline, with rounded corners. */
function OutlinePictogram({ Glyph, size, tone, label, className, radius }: { Glyph: PictogramComponent; size: keyof typeof sizeClass; tone: "neutral" | "brand"; label?: string; className?: string; radius: number }) {
  const [shape, setShape] = React.useState<PictogramShape | null | undefined>(() => cachedShape(Glyph))
  const probe = React.useRef<HTMLSpanElement>(null)
  // Measured once per pictogram (cached for every later one), before the first paint: no flash of the source drawing.
  React.useLayoutEffect(() => {
    if (shape !== undefined) return
    const svg = probe.current?.querySelector("svg")
    const s = svg ? measurePictogram(svg) : null
    rememberShape(Glyph, s)
    setShape(s)
  }, [Glyph, shape])
  const a11y = { "aria-hidden": label ? undefined : true, "aria-label": label, role: label ? "img" : undefined } as const
  const toneClass = tone === "brand" ? "text-primary" : "text-muted-foreground"

  // Not measured yet (the probe below) or can't be (no geometry): the source drawing, with Vita's line weight.
  if (!shape) {
    return (
      <span ref={probe} className={cn("relative inline-flex shrink-0", sizeClass[size], toneClass, className)}>
        <Glyph {...a11y} className="glyph size-full fill-current" />
      </span>
    )
  }

  const r = cornerUnits(radius)
  return (
    <span {...a11y} className={cn("relative inline-flex shrink-0", sizeClass[size], toneClass, className)}>
      <svg aria-hidden viewBox={`0 0 ${shape.w} ${shape.h}`} className="glyph size-full fill-current">
        {shape.parts.map((part, i) => <path key={i} fillRule="evenodd" d={part.map((c, j) => roundedPath(c, r, shape.holes[i][j])).join("")} />)}
      </svg>
    </span>
  )
}
