export type Section = "getting-started" | "foundations" | "components" | "patterns" | "decisions"

export interface NavEntry {
  slug: string
  title: string
}

export const manifest: Record<Section, NavEntry[]> = {
  "getting-started": [
    { slug: "installation", title: "Installation" },
    { slug: "cli", title: "CLI" },
    { slug: "skills", title: "Skills" },
    { slug: "registry", title: "Registry" },
    { slug: "about", title: "Mind, soul, body" },
    { slug: "brand", title: "Brand & voice" },
    { slug: "principles", title: "Design principles" },
    { slug: "interaction", title: "Interaction" },
    { slug: "changelog", title: "Changelog" },
  ],
  foundations: [
    { slug: "accessibility", title: "Accessibility" },
    { slug: "color", title: "Color" },
    { slug: "content", title: "Content, personas & taxonomy" },
    { slug: "corpus-for-ai", title: "Corpus for AI" },
    { slug: "grid", title: "Grid & layout" },
    { slug: "icons", title: "Icons" },
    { slug: "material", title: "Material" },
    { slug: "motion", title: "Motion" },
    { slug: "pictograms", title: "Pictograms" },
    { slug: "spacing", title: "Spacing" },
    { slug: "theming", title: "Theming & personalisation" },
    { slug: "typography", title: "Typography" },
  ],
  components: [
    { slug: "choosing-components", title: "Choosing a component" },
    { slug: "accordion", title: "Accordion" },
    { slug: "ai-label", title: "AI label" },
    { slug: "breadcrumb", title: "Breadcrumb" },
    { slug: "button", title: "Button" },
    { slug: "capsule", title: "Capsule" },
    { slug: "chat-bubble", title: "Chat bubble" },
    { slug: "checkbox", title: "Checkbox" },
    { slug: "code-snippet", title: "Code snippet" },
    { slug: "composer", title: "Composer" },
    { slug: "contained-list", title: "Contained list" },
    { slug: "content-switcher", title: "Content switcher" },
    { slug: "data-table", title: "Data table" },
    { slug: "date-picker", title: "Date picker" },
    { slug: "dropdown", title: "Dropdown" },
    { slug: "file-uploader", title: "File uploader" },
    { slug: "form", title: "Form" },
    { slug: "icon-placeholder", title: "Icon placeholder" },
    { slug: "inline-loading", title: "Inline loading" },
    { slug: "kpi", title: "KPI" },
    { slug: "link", title: "Link" },
    { slug: "list", title: "List" },
    { slug: "list-item", title: "List item" },
    { slug: "loading", title: "Loading" },
    { slug: "menu", title: "Menu" },
    { slug: "menu-buttons", title: "Menu buttons" },
    { slug: "modal", title: "Modal" },
    { slug: "notification", title: "Notification" },
    { slug: "number-input", title: "Number input" },
    { slug: "pagination", title: "Pagination" },
    { slug: "popover", title: "Popover" },
    { slug: "progress-bar", title: "Progress bar" },
    { slug: "progress-indicator", title: "Progress indicator" },
    { slug: "radio-button", title: "Radio button" },
    { slug: "search", title: "Search" },
    { slug: "select", title: "Select" },
    { slug: "slider", title: "Slider" },
    { slug: "structured-list", title: "Structured list" },
    { slug: "tabs", title: "Tabs" },
    { slug: "tag", title: "Tag" },
    { slug: "text-input", title: "Text input" },
    { slug: "tile", title: "Tile" },
    { slug: "timeline", title: "Timeline" },
    { slug: "toggle", title: "Toggle" },
    { slug: "tooltip", title: "Tooltip" },
    { slug: "tree-view", title: "Tree view" },
    { slug: "ui-shell-header", title: "UI shell header" },
    { slug: "ui-shell-left-panel", title: "UI shell left panel" },
    { slug: "ui-shell-right-panel", title: "UI shell right panel" },
  ],
  patterns: [
    { slug: "agent-conversation", title: "Agent conversation" },
    { slug: "common-actions", title: "Common actions" },
    { slug: "dialogs", title: "Dialogs" },
    { slug: "disabled-states", title: "Disabled states" },
    { slug: "disclosures", title: "Disclosures" },
    { slug: "empty-states", title: "Empty states" },
    { slug: "filtering", title: "Filtering" },
    { slug: "fluid-styles", title: "Fluid styles" },
    { slug: "forms", title: "Forms" },
    { slug: "global-header", title: "Global header" },
    { slug: "intent-first", title: "Intent-first input" },
    { slug: "list-items", title: "List items" },
    { slug: "loading", title: "Loading" },
    { slug: "login", title: "Login" },
    { slug: "notifications", title: "Notifications" },
    { slug: "overflow-content", title: "Overflow content" },
    { slug: "read-only-states", title: "Read-only states" },
    { slug: "right-panel", title: "Right panel" },
    { slug: "search", title: "Search" },
    { slug: "status-indicators", title: "Status indicators" },
    { slug: "text-toolbar", title: "Text toolbar" },
  ],
  decisions: [
    { slug: "how-we-decide", title: "How Corpus decides" },
    { slug: "glass-by-elevation", title: "Glass by elevation" },
    { slug: "status-semantics", title: "Status semantics" },
    { slug: "weather-tint", title: "Weather tint" },
    { slug: "buttons", title: "Buttons" },
    { slug: "motion", title: "Motion" },
    { slug: "fields-and-options", title: "Fields and options" },
  ],
}

export const sectionTitles: Record<Section, string> = {
  "getting-started": "Getting started",
  foundations: "Foundations",
  components: "Components",
  patterns: "Patterns",
  decisions: "Decisions",
}
