#!/usr/bin/env node
/**
 * Generates src/styles/palette.css, the primitive color layer.
 * 13 hues × 11 steps in OKLCH. Step 500 is the exact system color; other steps share its hue
 * and follow one lightness/chroma curve so every hue ramps identically.
 *
 * Primitives are NOT Tailwind utilities. Product code uses semantic tokens (bg-primary, text-error…).
 * Primitives exist for data visualisation and for defining new semantic tokens.
 */
import fs from "node:fs"
import path from "node:path"

const system = {
  red: "#FF3B30", orange: "#FF9500", yellow: "#FFCC00", green: "#34C759", mint: "#00C7BE", teal: "#30B0C7",
  cyan: "#32ADE6", blue: "#007AFF", indigo: "#5856D6", purple: "#AF52DE", pink: "#FF2D55", brown: "#A2845E", gray: "#8E8E93",
}
const steps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
const lightness = [0.975, 0.94, 0.88, 0.8, 0.72, null, 0.52, 0.44, 0.37, 0.3, 0.23]
const chromaCurve = [0.12, 0.28, 0.52, 0.78, 0.94, 1, 0.94, 0.84, 0.7, 0.55, 0.42]

const lin = (c) => ((c /= 255) <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
function oklch(hex) {
  const n = parseInt(hex.slice(1), 16)
  const r = lin((n >> 16) & 255), g = lin((n >> 8) & 255), b = lin(n & 255)
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s
  let H = (Math.atan2(B, A) * 180) / Math.PI
  if (H < 0) H += 360
  return { L, C: Math.hypot(A, B), H }
}

const lines = ["/* GENERATED by scripts/build-palette.mjs, do not edit. Primitive palette: data-viz + defining semantic tokens only. */", ":root {"]
const manifest = {}
for (const [name, hex] of Object.entries(system)) {
  const { L, C, H } = oklch(hex)
  manifest[name] = { base: hex, steps: {} }
  steps.forEach((step, i) => {
    const l = lightness[i] ?? L
    const c = i === 5 ? C : C * chromaCurve[i]
    const v = `oklch(${l.toFixed(3)} ${c.toFixed(3)} ${H.toFixed(1)})`
    lines.push(`  --vita-palette-${name}-${step}: ${v};`)
    manifest[name].steps[step] = v
  })
  lines.push("")
}
lines.push("}")
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..")
fs.writeFileSync(path.join(root, "src/styles/palette.css"), lines.join("\n") + "\n")
fs.writeFileSync(path.join(root, "src/styles/palette.json"), JSON.stringify({ steps, colors: manifest }, null, 2) + "\n")
console.log(`✓ palette: ${Object.keys(system).length} hues × ${steps.length} steps → src/styles/palette.css`)
